### ISSUE TITLE
Submitting Challenges

### ISSUE THREAD

**Issue by TravisSperry** [paircolumbus/Welcome#2]
Git cloned, added, commited CountingWords.git

When pushing branch...

`'remote: Permission to paircolumbus/CountingWords.git denied to travissperry.
fatal: unable to access 'https://github.com/paircolumbus/CountingWords.git/': The requested URL returned error: 403'`

Sorry if I missed this this morning, but these were the directions on submitting a challenge.

Thanks

**Comment by nickserv** [comment]
403 (Not Authorized) means you are not allowed to push the branch. It seems like you do not have permission to push to this repository directly. Instead, please fork this repository, push your code to your fork, and then send a pull request to this repository. If you need any help with this, let me know.

**Comment by TravisSperry** [comment]
Sounds good! Thanks.
